### ISSUE TITLE
Not adding 

### ISSUE THREAD

**Issue by queandres** [kahnu044/menu-by-user-roles#2] opened 2024-05-06 18:28 UTC
<img width="271" alt="Screenshot 2024-05-06 at 19 27 14" src="https://github.com/kahnu044/menu-by-user-roles/assets/169089568/cd2f30b6-4823-45ce-afd2-7a953598e5df">
Plugin gets stuck when trying to add an additional menu

**Comment by kahnu044** [comment] 2024-05-11 01:18
@queandres could you please mention the wordpress version as well as the plugin version?

**Comment by kahnu044** [comment] 2024-06-12 05:34
Hi @queandres,

We need more information to investigate this issue further. If you could provide the details requested above, it would help us resolve the problem.

If we don't hear back from you within the next week, we will close this issue. You can always reopen it or create a new issue if you have more information in the future.

Thank you!

**Comment by queandres** [comment] 2024-07-15 18:16
Hi Kanhu

Please see screenshot attached. Whenever I try to add new menu while plugin is activated, that wheel next to the Add to Menu button gets spinning and nothing happens.

**Comment by kahnu044** [comment] 2024-07-16 05:52
Hi @queandres,

Thank you for bringing this issue to our attention.

We have tested the plugin both in our local environment and in production, and it seems to be working fine on our end. It looks like the issue you're experiencing might be caused by a conflict with another plugin.

To help us better understand and resolve the issue, could you please share a screen recording of the problem? This will allow us to see exactly what's happening and work towards a solution more effectively.

We have attached a screen recording for you. Please check it and let us know if you need any further assistance.

Thank you.

https://github.com/user-attachments/assets/3f3cc04b-5668-42e9-9b57-2858c27f3296

**Comment by opicron** [comment] 2024-07-20 16:37
I confirm the plugin is working fine and does not interfere with add menu functionality on my websites. I checked the source code and see no way that it could interfere.

**Comment by kahnu044** [comment] 2024-07-22 06:42
Hi @opicron, 

Thank you for your feedback.

For now, I will close this issue as the plugin itself has been verified to be working correctly.

Thank you for your understanding and cooperation.

Best regards.

**Closed as completed by kahnu044** 2024-07-22 06:42 UTC
Labels: help wanted
